# Generated by Django 4.0.4 on 2022-04-29 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Figurine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(choices=[('officier', 'Officier'), ('independant', 'indépendant'), ('troupier', 'troupier')], default='troupier', max_length=30)),
                ('hit', models.IntegerField(blank=True)),
                ('move', models.IntegerField()),
                ('fight', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('health', models.IntegerField()),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helldorado.faction')),
                ('keywords', models.ManyToManyField(to='helldorado.keywords')),
            ],
        ),
    ]
