# Generated by Django 4.0.4 on 2022-04-29 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helldorado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_inscription', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='figurine',
            name='frequence',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helldorado.faction')),
                ('liste', models.ManyToManyField(to='helldorado.figurine')),
            ],
        ),
    ]
